# Generated by Django 2.2.3 on 2022-10-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoPcd',
            fields=[
                ('alu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('alu_nome', models.CharField(max_length=255)),
                ('alu_cpf', models.CharField(max_length=11)),
                ('alu_sexo', models.CharField(max_length=1)),
                ('alu_email', models.CharField(max_length=255)),
                ('alu_telefone', models.CharField(max_length=255)),
                ('alu_matricula', models.CharField(max_length=11)),
                ('alu_deficiencias', models.CharField(blank=True, max_length=255, null=True)),
                ('alu_periodo_academico', models.CharField(db_column='alu_Periodo_Academico', max_length=255)),
                ('alu_data_nascimento', models.DateField()),
            ],
            options={
                'db_table': 'aluno_pcd',
                'managed': False,
            },
        ),
    ]
