# Generated by Django 4.1.1 on 2022-10-07 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('avi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('avi_titulo', models.CharField(max_length=255)),
                ('avi_descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('avi_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('avi_arquivos', models.TextField(blank=True, null=True)),
                ('avi_mostrar', models.BooleanField(default=True)),
            ],
        ),
    ]
