# Generated by Django 2.2.3 on 2022-10-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisos',
            name='avi_mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
