# Generated by Django 4.1.1 on 2022-10-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisos',
            options={'managed': False},
        ),
    ]
