# Generated by Django 4.1.1 on 2022-10-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_alter_avisos_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avisos',
            table='avisos',
        ),
    ]
