# Generated by Django 2.2.3 on 2022-10-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('adm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('adm_nome', models.CharField(max_length=255)),
                ('adm_cpf', models.CharField(max_length=11)),
                ('adm_email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
    ]
