# Generated by Django 4.1.1 on 2022-10-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('adm_id', models.AutoField(db_column='adm_id', primary_key=True, serialize=False)),
                ('adm_nome', models.CharField(db_column='adm_nome', max_length=255)),
                ('adm_cpf', models.CharField(db_column='adm_cpf', max_length=11)),
                ('adm_email', models.EmailField(db_column='adm_email', max_length=255)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
    ]
