# Generated by Django 2.2.3 on 2022-10-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('mon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mon_nome', models.CharField(max_length=255)),
                ('mon_cpf', models.CharField(max_length=11)),
                ('mon_sexo', models.CharField(max_length=1)),
                ('mon_email', models.CharField(max_length=255)),
                ('mon_telefone', models.CharField(max_length=255)),
                ('mon_matricula', models.CharField(max_length=11)),
                ('mon_periodo_academico', models.CharField(max_length=255)),
                ('mon_tipo', models.CharField(max_length=7)),
                ('mon_arquivos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tut_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tut_nome', models.CharField(max_length=255)),
                ('tut_cpf', models.CharField(max_length=11)),
                ('tut_sexo', models.CharField(max_length=1)),
                ('tut_email', models.CharField(max_length=255)),
                ('tut_telefone', models.CharField(max_length=255)),
                ('tut_matricula', models.CharField(max_length=11)),
                ('tut_periodo_academico', models.CharField(max_length=255)),
                ('tut_tipo', models.CharField(max_length=7)),
                ('tut_arquivos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
    ]
