# Generated by Django 4.1.1 on 2022-10-01 20:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('mon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mon_nome', models.CharField(max_length=255)),
                ('mon_cpf', models.CharField(max_length=11)),
                ('mon_sexo', models.CharField(max_length=1)),
                ('mon_email', models.CharField(max_length=255)),
                ('mon_telefone', models.CharField(max_length=255)),
                ('mon_matricula', models.CharField(max_length=11)),
                ('mon_periodo_academico', models.CharField(max_length=255)),
                ('mon_tipo', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'monitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tut_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tut_nome', models.CharField(max_length=255)),
                ('tut_cpf', models.CharField(max_length=11)),
                ('tut_sexo', models.CharField(max_length=1)),
                ('tut_email', models.CharField(max_length=255)),
                ('tut_telefone', models.CharField(max_length=255)),
                ('tut_matricula', models.CharField(max_length=11)),
                ('tut_periodo_academico', models.CharField(max_length=255)),
                ('tut_tipo', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_administrador', models.BooleanField(default=False)),
                ('is_aluno', models.BooleanField(default=False)),
                ('is_interprete', models.BooleanField(default=False)),
                ('is_monitor', models.BooleanField(default=False)),
                ('is_tutor', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('adm_nome', models.CharField(max_length=255)),
                ('adm_cpf', models.CharField(max_length=11)),
                ('adm_email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlunoPcd',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alu_telefone', models.CharField(max_length=255)),
                ('alu_matricula', models.CharField(max_length=11)),
                ('alu_deficiencias', models.CharField(blank=True, max_length=255, null=True)),
                ('alu_periodo_academico', models.CharField(db_column='alu_Periodo_Academico', max_length=255)),
                ('alu_data_nascimento', models.DateField()),
            ],
            options={
                'db_table': 'aluno_pcd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interprete',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('int_nome', models.CharField(max_length=255)),
                ('int_cpf', models.CharField(max_length=11)),
                ('int_sexo', models.CharField(max_length=1)),
                ('int_email', models.CharField(max_length=255)),
                ('int_telefone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'interprete',
                'managed': False,
            },
        ),
    ]
