# Generated by Django 4.1.1 on 2022-10-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_user_cpf_remove_user_nome_remove_user_sexo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alunopcd',
            options={},
        ),
        migrations.AlterModelOptions(
            name='interprete',
            options={},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={},
        ),
    ]
