# Generated by Django 2.2.3 on 2022-10-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('cur_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cur_descricao', models.CharField(max_length=255)),
                ('cur_quant_periodos', models.IntegerField()),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('dis_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dis_descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'disciplinas',
                'managed': False,
            },
        ),
    ]
