from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.admIndex, name='admIndex'),
    path('homologar/', views.homologar, name='homologar'),
    path('alunos/', views.adminAlunos, name='alunos'),
    path('adicionarAluno', views.adicionarAluno, name='adicionarAluno'),
    path('buscarAluno', views.buscarAluno, name='buscarAluno'),
    path('<int:aluno_id>', views.admAluno, name='admAluno'),
    path('atualizarAluno/<int:aluno_id>', views.atualizarAluno, name='atualizarAluno'),
    path('deletarAluno/<int:aluno_id>', views.deletarAluno, name='deletarAluno'),
    path('monitores/', views.adminMonitores, name='monitores'),
    path('adicionarMonitor', views.adicionarMonitor, name='adicionarMonitor'),
    path('buscarMonitor', views.buscarMonitor, name='buscarMonitor'),
    path('<int:monitor_id>', views.admMonitor, name='admMonitor'),
    path('atualizarMonitor/<int:monitor_id>', views.atualizarMonitor, name='atualizarMonitor'),
    path('deletarMonitor/<int:monitor_id>', views.deletarMonitor, name='deletarMonitor'),
    path('tutores/', views.adminTutores, name='tutores'),
    path('adicionarTutor', views.adicionarTutor, name='adicionarTutor'),
    path('buscarTutor', views.buscarTutor, name='buscarTutor'),
    path('<int:tutor_id>', views.admTutor, name='admTutor'),
    path('atualizarTutor/<int:tutor_id>', views.atualizarTutor, name='atualizarTutor'),
    path('deletarTutor/<int:tutor_id>', views.deletarTutor, name='deletarTutor'),
    path('interpretes/', views.adminInterpretes, name='interpretes'),
    path('adicionarInterprete', views.adicionarInterprete, name='adicionarInterprete'),
    path('buscarInterprete', views.buscarInterprete, name='buscarInterprete'),
    path('<int:interprete_id>', views.admInterprete, name='admInterprete'),
    path('atualizarInterprete/<int:interprete_id>', views.atualizarInterprete, name='atualizarInterprete'),
    path('deletarInterprete/<int:interprete_id>', views.deletarInterprete, name='deletarInterprete'),
]