# Generated by Django 4.1.1 on 2022-10-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interprete',
            fields=[
                ('int_id', models.AutoField(db_column='int_id', primary_key=True, serialize=False)),
                ('int_nome', models.CharField(db_column='int_nome', max_length=255)),
                ('int_cpf', models.CharField(db_column='int_cpf', max_length=11)),
                ('int_genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], db_column='int_genero', max_length=1)),
                ('int_email_pessoal', models.EmailField(db_column='int_email_pessoal', max_length=255)),
                ('int_email_institucional', models.EmailField(db_column='int_email_institucional', max_length=255)),
                ('int_telefone', models.CharField(db_column='int_telefone', max_length=255)),
            ],
            options={
                'db_table': 'interprete',
                'managed': False,
            },
        ),
    ]
